import type { D } from "@/i18n/dict";

export type Lang = "en" | "vi";

export interface LocaleTranslation {
  en: string;
  vi: string;
}

export interface Dict {
  [key: string]: LocaleTranslation;
}

export interface ReplaceOptions {
  [key: string]: string | number;
}

/**
 * @param T - The object type to extract leaves from.
 * @returns A union of dot-notation paths representing the leaves of the object T.
 * @example
 * - Given an object type:
 * ```typescript
 * type Example = {
 * * a: {
 * * * b: {
 * * * * c: string;
 * * * * d: number;
 * * * };
 * * * e: {
 * * * * DEFAULT: string; // Special fallback node generated by split script
 * * * * all: string;
 * * * };
 * * };
 * };
 * ```
 * * The resulting type Leaves<Example> would be:
 * "a.b.c" | "a.b.d" | "a.e.DEFAULT" | "a.e.all"
 * * This utility type recursively traverses the object type T and constructs 
 * dot-notation paths for each leaf property to guarantee strict compile-time type safety.
 */
export type Leaves<T> = T extends object
  ? { [K in keyof T]-?: Join<K, Leaves<T[K]>> }[keyof T]
  : "";

/**
 * @param K - The current key in the object.
 * @param P - The accumulated path from the root to the current key.
 * @returns A dot-notation path string representing the full path to the leaf property.
 * 
 * This utility type constructs a dot-notation path by concatenating the current key K with the accumulated path P.
 * If P is an empty string, it returns just K; otherwise, it returns "K.P".
 * This allows for the recursive construction of paths as we traverse the object type.
 */
export type Join<K, P> = K extends string | number
  ? P extends string | number
  ? P extends ""
  ? `${K}`
  : `${K}.${P}`
  : `${K}`
  : "";

// Định nghĩa Type an toàn cho Key dựa trên file tiếng Việt làm chuẩn gốc
export type TxKey = Leaves<(typeof D)["vi"]>;

export interface I18nContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TxKey, replaceOptions?: ReplaceOptions) => string;
}